services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=dinizcourse'
      - 'MYSQL_PASSWORD=1234567'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=root'
    ports:
      - '3306'
